cfg:
  nemo_path: ./intent_slot_model.nemo
  data_dir: ./data
  class_labels:
    intent_labels_file: ./data/dict.intents.csv
    slot_labels_file: ./data/dict.slots.csv
  class_balancing: {}
  intent_loss_weight: 0.6
  pad_label: -1
  ignore_extra_tokens: false
  ignore_start_end: true
  train_ds:
    prefix: train
    batch_size: 16
    shuffle: true
    num_samples: -1
    num_workers: 4
    drop_last: false
    pin_memory: true
  validation_ds:
    prefix: val
    batch_size: 16
    shuffle: false
    num_samples: -1
    num_workers: 4
    drop_last: false
    pin_memory: true
  test_ds:
    prefix: test
    batch_size: 16
    shuffle: false
    num_samples: -1
    num_workers: 4
    drop_last: false
    pin_memory: true
  tokenizer:
    tokenizer_name: distilbert-base-uncased
    vocab_file: /home/sammy/.cache/huggingface/nemo_nlp_tmp/509a2d7eeb967548a5deb5a4940ad609/vocab.txt
    tokenizer_model: null
    special_tokens: null
  language_model:
    max_seq_length: 64
    pretrained_model_name: distilbert-base-uncased
    lm_checkpoint: null
    config_file: ../models/nlp/distilbert-base-uncased_encoder_config.json
    config: null
  head:
    num_output_layers: 1
    fc_dropout: 0.1
  optim:
    name: adam
    lr: 2.0e-05
    args:
      name: auto
      weight_decay: 0.01
    sched:
      name: WarmupAnnealing
      iters_per_batch: null
      max_steps: -1
      monitor: val_loss
      reduce_on_plateau: false
      args:
        name: auto
        warmup_steps: null
        warmup_ratio: 0.1
        last_epoch: -1
  data_desc:
    intent_labels:
    - book_container
    - cancel_container
    - check_container
    - list_containers
    - check_container_status
    - list_containers_by_location
    - schedule_maintenance
    - query_ship_schedule
    - query_ship_location
    - update_container_destination
    - check_equipment_status
    - book_shipment
    - cancel_shipment
    - cancel_equipment
    - list_equipment_by_location
    intent_label_ids:
      book_container: 0
      cancel_container: 1
      check_container: 2
      list_containers: 3
      check_container_status: 4
      list_containers_by_location: 5
      schedule_maintenance: 6
      query_ship_schedule: 7
      query_ship_location: 8
      update_container_destination: 9
      check_equipment_status: 10
      book_shipment: 11
      cancel_shipment: 12
      cancel_equipment: 13
      list_equipment_by_location: 14
    intent_weights:
    - 0.5769230769230769
    - 1.1538461538461537
    - 1.1538461538461537
    - 1.1538461538461537
    - 1.1538461538461537
    - 1.1538461538461537
    - 1.1538461538461537
    - 1.1538461538461537
    - 1.1538461538461537
    - 0.5769230769230769
    - 1.1538461538461537
    - 1.1538461538461537
    - 1.1538461538461537
    - 1.0
    - 1.0
    slot_labels:
    - B-date
    - I-date
    - B-container_name
    - I-container_name
    - B-location
    - I-location
    - B-equipment_type
    - I-equipment_type
    - B-equipment_id
    - I-equipment_id
    - B-ship_name
    - I-ship_name
    - B-cargo_type
    - I-cargo_type
    - O
    slot_label_ids:
      B-date: 0
      I-date: 1
      B-container_name: 2
      I-container_name: 3
      B-location: 4
      I-location: 5
      B-equipment_type: 6
      I-equipment_type: 7
      B-equipment_id: 8
      I-equipment_id: 9
      B-ship_name: 10
      I-ship_name: 11
      B-cargo_type: 12
      I-cargo_type: 13
      O: 14
    slot_weights:
    - 4.3
    - 8.6
    - 1.4333333333333333
    - 1.0
    - 8.6
    - 1.0
    - 8.6
    - 1.0
    - 8.6
    - 1.0
    - 4.3
    - 1.0
    - 4.3
    - 8.6
    - 0.1246376811594203
    pad_label: 14
  target: nemo.collections.nlp.models.intent_slot_classification.intent_slot_classification_model.IntentSlotClassificationModel
  nemo_version: 2.4.0
